name: Deploy Documentation

# This workflow only runs when a release is created, if a draft is published as a release, or if a prerelease
# is updated to a release (the prerelease checkbox is disabled).
#
# The `deploy-documentation` job also requires that the release has an asset named `Documentation.zip`,
# otherwise the workflow itself will run, but the job will not.

on:
  release:
    types: [released]

jobs:
  deploy-documentation:
    if: ${{ contains(github.event.release.assets.*.name, 'Documentation.zip') }}
    runs-on: ubuntu-latest

    steps:
    - name: Download Documentation
      uses: dsaltares/fetch-gh-release-asset@master
      with:
        file: Documentation.zip
        version: ${{ github.event.release.id }}
        target: ./Documentation.zip

    - name: Decompress
      run: unzip -o ./Documentation.zip -d ./docs

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
